### PR TITLE
slog mains

### PR DESCRIPTION
**Pull request by brianolson**
add integration into main()s for slog, set level, output file, log rotation rules, text or json

stack on https://github.com/bluesky-social/indigo/pull/858

### CODE REVIEW

**Comment by bnewbold** [comment]
I feel a bit meh about adding logrotate and other complex stuff like that. do we use any `go-log` functionality other than setting the log level, anywhere in our stack? I think we basically log out to stdout/stderr everywhere, and use other daemons/systems to manage the stream of logs (eg, implement log rotation, shipping to relevant log indexing services, etc).

but I care more about getting the `log/slog` refactor merged than I do nit-picking around log infra generally.

**Comment by brianolson** [comment]
relay works better logging directly to file and the rotation stuff has been exercised in recent gigarelay experiments

**Comment by brianolson** [comment]
this is replaced by https://github.com/bluesky-social/indigo/pull/866 which is the same stuff but against `main` after https://github.com/bluesky-social/indigo/pull/856 has merged

**Comment by brianolson** [comment]
merged as https://github.com/bluesky-social/indigo/pull/866

**Pull request closed without merging**
